### ISSUE TITLE
The example don't work

### ISSUE THREAD

**Issue by yamadi** [gunthercox/chatterbot-weather#2]
I run the example you give .but it not give the answer.
And I debug the code , find that the procedure  is not enter weather.py
I do not know cause my configuration issues or other reasons。
Can you help me ?

**Comment by gunthercox** [comment]
Hi, I've made a small change to the example included in this project. I've manually set the input and output adapter to use the corresponding terminal adapter. I believe this should solve the issue. Please let me know if this works for you.

**Comment by yamadi** [comment]
HI, it not work after the change,I think the main reason is that the  script of **weather.py**   is not be invoked. @gunthercox

**Comment by yamadi** [comment]
Hi, i try again, it not work.


and the result is :


it seems that the code not work.

Take your time for solve this problem ,Thanks.


750539669@qq.com
 
From: Gunther Cox
Date: 2016-07-09 09:07
To: gunthercox/chatterbot-weather
CC: yamadi; Author
Subject: Re: [gunthercox/chatterbot-weather] The example don't work (#2)
Hi, I've made a small change to the example included in this project. I've manually set the input and output adapter to use the corresponding terminal adapter. I believe this should solve the issue. Please let me know if this works for you.

**Comment by yamadi** [comment]
Thank you,I know the reason.My problem.. @gunthercox
